galaxy_info:
  author: Peter Metz <peter.metz@ionos.com>
  description: Install and configure Docker CE and friends
  company: IONOS Cloud

  min_ansible_version: 2.1

  platforms:
  - name: Debian
    versions:
      - all
  - name: Ubuntu
    versions:
      - focal
      - jammy

  galaxy_tags: []


dependencies: []