# vim: ts=2: sw=2: ai: si
# CI workflow

name: CI

on:
    workflow_dispatch:
    pull_request:
        types: [ assigned, opened, synchronize, reopened ]
    push:
      branches: [ master ]

jobs:

  test:

    name: Testing the Ansible Module
    env:
        python-version: 3.9.0
        ionoscloud-version: 6.0.0b8

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
        python-version: ${{ env.python-version }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checkout sdk-resources
      - name: Checkout module-ansible
        uses: actions/checkout@v2
        with:
          path: resources
          ref: feat/implement-cloudapi-v6-features


      - name: Setup Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - name: Setup pip, virtualenv, twine, wheel
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          pip install twine
          pip install wheel
          pip install -i https://test.pypi.org/simple/ ionoscloud==${{ env.ionoscloud-version }}

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          IONOS_USERNAME: ${{ secrets.IONOS_VDC_USER }}
          IONOS_PASSWORD: ${{ secrets.IONOS_VDC_PASSWORD }}
        with:
          playbook: datacenter-test.yml
          directory: module-ansible/tests
